// Glass Palette runtime (theme.js). GENERATED by build.py from src/*.css + src/runtime.js. Edit those, then rebuild.
// It only paints. It never writes Spotify's own full-screen colour property, which govee-dj.js reads for the lights.
(function officeGlass() {
  if (!document.head || !document.body) { setTimeout(officeGlass, 300); return; }
  // Spicetify normally loads user.css itself. Keep the bundled copy as a Marketplace fallback, but never parse and
  // paint both copies at once. The duplicate 290 KB sheet was doubling selector matching, font decoding and repaints.
  const syncThemeCss = () => {
    const linkedCssLive = [...document.querySelectorAll('link.userCSS')].some((link) => !link.disabled && link.sheet);
    let style = document.getElementById('office-glass');
    if (linkedCssLive) { if (style) style.remove(); return; }
    if (!style) { style = document.createElement('style'); style.id = 'office-glass'; document.head.appendChild(style); }
    if (!style.textContent) style.textContent = __CSS__;
  };
  syncThemeCss();
  if (window.__officeGlassCssObserver) window.__officeGlassCssObserver.disconnect();
  window.__officeGlassCssObserver = new MutationObserver(syncThemeCss);
  window.__officeGlassCssObserver.observe(document.head, { childList: true, attributes: true, attributeFilter: ['disabled', 'href', 'media'] });
  // The system's "reduce motion" switch is honoured by default. A screen can have it on and still want the
  // beat: localStorage['office-glass-motion'] = 'always' overrides it (or 'never' to keep the stage still).
  const reducedMotionQuery = window.matchMedia('(prefers-reduced-motion: reduce)');
  const reducedMotion = { get matches() { const m = localStorage.getItem('office-glass-motion'); return m === 'never' || (m !== 'always' && reducedMotionQuery.matches); } };
  // a re-injection (live iteration) rebuilds its own elements from scratch
  for (const old of document.querySelectorAll('#office-glass-capsules, #office-glass-title, #office-glass-backdrop')) old.remove();

  const hsv = (r, g, b) => { r /= 255; g /= 255; b /= 255; const mx = Math.max(r, g, b), mn = Math.min(r, g, b), d = mx - mn; let h = 0; if (d) { if (mx === r) h = ((g - b) / d + 6) % 6; else if (mx === g) h = (b - r) / d + 2; else h = (r - g) / d + 4; } return [h / 6, mx ? d / mx : 0, mx]; };
  const rgb = (h, sa, v) => { h = ((h % 1) + 1) % 1 * 6; const c = v * sa, x = c * (1 - Math.abs((h % 2) - 1)), m = v - c; const [r, g, b] = h < 1 ? [c, x, 0] : h < 2 ? [x, c, 0] : h < 3 ? [0, c, x] : h < 4 ? [0, x, c] : h < 5 ? [x, 0, c] : [c, 0, x]; return [r + m, g + m, b + m].map((n) => Math.round(n * 255)).join(' '); };
  let lastHex = null, lastCoverUrl = null;
  // outside full screen there is no Spotify colour to read: take the cover's strongest hue instead
  const colourFromCover = () => {
    let url = null;
    try { const md = Spicetify.Player.data.item.metadata; url = (md.image_url || md.image_large_url || '').replace('spotify:image:', 'https://i.scdn.co/image/'); } catch (e) {}
    if (!url || url === lastCoverUrl) return;
    lastCoverUrl = url;
    // if this track has already shown its full-screen colour (Spotify's own pick), the app view reuses it so both agree
    try { const uri = Spicetify.Player.data.item.uri; const seen = window.__ogSeenHex && window.__ogSeenHex[uri]; if (seen) { const n = parseInt(seen, 16); applyColour((n >> 16) & 255, (n >> 8) & 255, n & 255); return; } } catch (e) {}
    const img = new Image(); img.crossOrigin = 'anonymous';
    img.onload = () => {
      try {
        const c = document.createElement('canvas'); c.width = c.height = 40;
        const x = c.getContext('2d', { willReadFrequently: true }); x.drawImage(img, 0, 0, 40, 40);
        const px = x.getImageData(0, 0, 40, 40).data, bins = new Array(24).fill(0), sums = Array.from({ length: 24 }, () => [0, 0, 0]);
        for (let i = 0; i < px.length; i += 4) {
          const [h, sa, v] = hsv(px[i], px[i + 1], px[i + 2]); const w = sa * sa * v; if (w < 0.04) continue;
          const b = Math.floor(h * 24) % 24; bins[b] += w; sums[b][0] += px[i] * w; sums[b][1] += px[i + 1] * w; sums[b][2] += px[i + 2] * w;
        }
        const best = bins.indexOf(Math.max(...bins));
        if (bins[best] < 1.5) { applyColour(150, 165, 175); return; }
        applyColour(sums[best][0] / bins[best], sums[best][1] / bins[best], sums[best][2] / bins[best]);
      } catch (e) {}
    };
    img.src = url;
  };
  // ---- a cover with no picture in it ----
  // Some album art is a single flat colour. Donda is a black square: every pixel is rgb(3, 3, 3), nothing else.
  // Framed like a photograph it stops reading as artwork and starts reading as a hole cut in the panel. Measure
  // the cover and say so, and the CSS treats it as a pane of glass instead. The test is deliberately strict: dark
  // AND uniform, so the only covers that get it are ones with provably no detail to throw away.
  let lastFlatUrl = null;
  const flatArt = () => {
    let url = null;
    try { const md = Spicetify.Player.data.item.metadata; url = (md.image_url || md.image_large_url || '').replace('spotify:image:', 'https://i.scdn.co/image/'); } catch (e) {}
    if (!url || url === lastFlatUrl) return;
    lastFlatUrl = url;
    const img = new Image(); img.crossOrigin = 'anonymous';
    img.onload = () => {
      try {
        const c = document.createElement('canvas'); c.width = c.height = 24;
        const x = c.getContext('2d', { willReadFrequently: true }); x.drawImage(img, 0, 0, 24, 24);
        const px = x.getImageData(0, 0, 24, 24).data;
        let sum = 0, mn = 255, mx = 0, n = 0;
        for (let i = 0; i < px.length; i += 4) {
          const l = 0.2126 * px[i] + 0.7152 * px[i + 1] + 0.0722 * px[i + 2];
          sum += l; if (l < mn) mn = l; if (l > mx) mx = l; n++;
        }
        document.documentElement.classList.toggle('office-glass-flatart', sum / n < 26 && mx - mn < 26);
      } catch (e) {}
    };
    img.src = url;
  };
  // ---- lyrics on our own clock ("lyrics feel slower than reality") ----
  // Spotify lights a line when its own player position crosses the line's time; on a Connect speaker (a Sonos, say) the
  // sound is ahead of that. So we fetch the line times ourselves and run the highlight from the player position
  // plus a lead. Knob: localStorage['office-glass-lyric-lead-ms'] (default 350, + = earlier). If the fetched lines
  // do not match the page, Spotify's own labelling below stays in charge.
  let lyricTimes = null, lyricFor = null;
  const lyricLead = () => +(localStorage.getItem('office-glass-lyric-lead-ms') || 350);
  const fetchLyricTimes = async () => {
    let id = null; try { const u = Spicetify.Player.data.item.uri; id = u.startsWith('spotify:track:') ? u.split(':')[2] : null; } catch (e) {}
    if (!id || lyricFor === id) return;
    lyricFor = id; lyricTimes = null;
    try {
      const tok = (Spicetify.Platform.Session && Spicetify.Platform.Session.accessToken) || (await Spicetify.Platform.AuthorizationAPI.getState()).token.accessToken;
      const r = await fetch('https://spclient.wg.spotify.com/color-lyrics/v2/track/' + id + '?format=json&vocalRemoval=false&market=from_token', { headers: { Authorization: 'Bearer ' + tok, 'app-platform': 'WebPlayer' } });
      if (!r.ok) return;
      const b = await r.json();
      if (lyricFor === id && b.lyrics && b.lyrics.syncType === 'LINE_SYNCED') lyricTimes = b.lyrics.lines.map((l) => +l.startTimeMs);
    } catch (e) { /* no lyrics: Spotify's labelling stays */ }
  };
  const clockLyrics = (box) => {
    if (!lyricTimes || lyricTimes.length < 3) return false;
    const lines = [...box.querySelectorAll('div[dir]')].filter((l) => (l.textContent || '').trim() !== '');
    if (lines.length !== lyricTimes.length) return false;
    let pos = 0; try { pos = Spicetify.Player.getProgress() + lyricLead(); } catch (e) { return false; }
    let active = -1; for (let i = 0; i < lyricTimes.length; i++) { if (lyricTimes[i] <= pos) active = i; else break; }
    if (active < 0) active = 0;
    const ar = lines[active].getBoundingClientRect(), view = (document.querySelector('.Root__main-view') || document.body).getBoundingClientRect();
    document.documentElement.classList.toggle('office-glass-lyrics-free', ar.bottom < view.top + 40 || ar.top > view.bottom - 40);
    lines.forEach((l, i) => {
      const og = i < active ? 'passed' : i === active ? 'active' : 'next', d = String(Math.min(6, Math.abs(i - active)));
      if (l.dataset.og !== og) l.dataset.og = og;
      if (l.style.getPropertyValue('--d') !== d) l.style.setProperty('--d', d);
    });
    return true;
  };
  setInterval(fetchLyricTimes, 1500);
  // ---- the artist's own photographs ----
  // One GraphQL request per artist, kept on the document so both the full-screen stage and the right panel's
  // "About the artist" card can use it. It used to be fetched inside the full-screen title swap, which meant the
  // panel never saw it outside full screen.
  let artistKey = null;
  const artistVisuals = () => {
    const it = Spicetify.Player.data && Spicetify.Player.data.item;
    const au = (it && it.artists && it.artists[0] && it.artists[0].uri) || '';
    if (!au || au === artistKey) return;
    artistKey = au; window.__ogArtistFace = null;
    document.documentElement.style.removeProperty('--og-scene');
    if (!au.startsWith('spotify:artist:') || !Spicetify.GraphQL) return;
    Spicetify.GraphQL.Request(Spicetify.GraphQL.Definitions.queryArtistOverview, { uri: au, locale: '', includePrerelease: false }).then((g) => {
      if (artistKey !== au) return;                                    // the song moved on while we were asking
      const vis = (((g || {}).data || {}).artistUnion || {}).visuals || {};
      const list = (vis.avatarImage && vis.avatarImage.sources) || [];
      const face = list.slice().sort((x, y) => x.width - y.width).find((x) => x.width >= 150) || list[0];
      if (face) window.__ogArtistFace = face.url;
      const gal = (vis.gallery && vis.gallery.items) || [];            // the editorial photograph, wide, for backdrops
      const wide = gal.map((x) => (x.sources || []).slice().sort((a, b) => b.width - a.width)[0]).filter(Boolean)[0] || list.slice().sort((a, b) => b.width - a.width)[0];
      if (wide) document.documentElement.style.setProperty('--og-scene', 'url("' + wide.url + '")');
    }).catch(() => {});
  };

  // The right panel's "About the artist" card carries only hashed class names, so tag it ourselves: it is the card
  // holding an image whose alt is the playing artist. Then the theme can dress it without guessing at Spotify's
  // build-specific classes.
  const tagAbout = () => {
    const m = document.querySelector('.main-nowPlayingView-mainContainer');
    if (!m) return;
    const it = Spicetify.Player.data && Spicetify.Player.data.item;
    const name = (it && it.artists && it.artists[0] && it.artists[0].name) || '';
    if (!name) return;
    const img = [...m.querySelectorAll('img[alt]')].find((i) => i.alt === name && i.closest('figure'));
    if (!img) return;
    let card = img.closest('figure');
    for (let i = 0; i < 5 && card && card.parentElement && card.getBoundingClientRect().width < 200; i++) card = card.parentElement;
    // that lands on the card's header row; the card itself is the outermost box of the same width
    for (let i = 0; i < 4 && card && card.parentElement && card.parentElement !== m; i++) {
      if (Math.abs(card.parentElement.getBoundingClientRect().width - card.getBoundingClientRect().width) > 3) break;
      card = card.parentElement;
    }
    if (!card || card.classList.contains('og-about')) return;
    for (const old of m.querySelectorAll('.og-about')) old.classList.remove('og-about');
    card.classList.add('og-about');
    img.closest('figure').classList.add('og-about-face');
  };

  // lyrics: label every line passed / active / next and how far it is from the sung line, for the depth-of-field look
  let lyricsBox = null, lyricsObs = null;
  const labelLyrics = () => {
    const box = document.querySelector('[style*="--lyrics-color-active"]');
    if (box !== lyricsBox) {                                                // a new lyrics page: watch it for line changes
      if (lyricsObs) lyricsObs.disconnect();
      lyricsBox = box; lyricsObs = null;
      if (box) { lyricsObs = new MutationObserver(() => labelLyrics()); lyricsObs.observe(box, { subtree: true, attributes: true, attributeFilter: ['class'], childList: true }); }
    }
    if (!box) return;
    if (clockLyrics(box)) return;                                            // our own clock ran the lines
    const lines = [...box.querySelectorAll('div[dir]')];
    if (lines.length < 3) return;
    const count = {}; lines.forEach((l) => { count[l.className] = (count[l.className] || 0) + 1; });
    let active = lines.findIndex((l) => count[l.className] === 1);          // the sung line is the only one with its class
    if (active < 0) { lines.forEach((l) => { if (l.dataset.og) { delete l.dataset.og; l.style.removeProperty('--d'); } }); return; }   // unsynced lyrics: leave them plain
    // is the sung line on screen? If not, the person is browsing: drop the depth-of-field
    const ar = lines[active].getBoundingClientRect(), view = (document.querySelector('.Root__main-view') || document.body).getBoundingClientRect();
    document.documentElement.classList.toggle('office-glass-lyrics-free', ar.bottom < view.top + 40 || ar.top > view.bottom - 40);
    lines.forEach((l, i) => {
      const og = i < active ? 'passed' : i === active ? 'active' : 'next', d = String(Math.min(6, Math.abs(i - active)));
      if (l.dataset.og !== og) l.dataset.og = og;
      if (l.style.getPropertyValue('--d') !== d) l.style.setProperty('--d', d);
    });
  };
  // ---- the song's Canvas behind the lyrics ("the one beside, video gif one") ----
  // Spotify's Canvas is the short looping video it plays beside a song. Its plain .mp4 is H.264, which this browser
  // cannot decode, so this does what Spotify's own Canvas player does: ask Spotify's canvas query for the file id,
  // ask Spotify's manifest service which versions exist, and take the WebM (VP9) one at 480 px wide, which is plenty
  // for a softened background. The pieces (an 8 s loop is about 1.3 MB) come from Spotify's video CDN and are fed
  // to the <video> through MediaSource. Every address is checked before it is fetched: the manifest only from
  // spclient.wg.spotify.com, the pieces only from video-*.spotifycdn.com or video-*.scdn.co, and no more than 8 MB.
  // It loads only while lyrics are on screen, plays muted and looping, holds still while the music is paused, and
  // a song without a Canvas (or any failure) keeps the wallpaper. Settings > Lyrics turns it off.
  const CANVAS_TYPE = 'video/webm; codecs="vp9"';
  let canvasKey = null, canvasBufs = null, canvasLoading = null;
  const loadCanvas = async (uri) => {
    const g = await Spicetify.GraphQL.Request(Spicetify.GraphQL.Definitions.canvas, { trackUri: uri });
    const c = g && g.data && g.data.trackUnion && g.data.trackUnion.canvas;
    if (!c || !/VIDEO/.test(c.type || '') || !/^[0-9a-f]{32}$/.test(c.fileId || '')) return null;
    const tok = (Spicetify.Platform.Session && Spicetify.Platform.Session.accessToken) || (await Spicetify.Platform.AuthorizationAPI.getState()).token.accessToken;
    const m = await (await fetch('https://spclient.wg.spotify.com/manifests/v9/json/sources/' + c.fileId + '/options/supports_drm', { headers: { authorization: 'Bearer ' + tok } })).json();
    const k = m && m.contents && m.contents[0];
    if (!k || (k.encryption_infos && k.encryption_infos.length) || !window.MediaSource || !MediaSource.isTypeSupported(CANVAS_TYPE)) return null;
    const webm = (k.profiles || []).filter((p) => p.file_type === 'webm' && /vp9/.test(p.video_codec || '')).sort((a, b) => a.video_width - b.video_width);
    const p = webm.find((x) => x.video_width >= 480) || webm[webm.length - 1];
    const base = (m.base_urls || []).find((u) => /^https:\/\/video-[a-z]+\.(spotifycdn\.com|scdn\.co)\/segments\/$/.test(u));
    const tmplOk = (t) => typeof t === 'string' && t.startsWith('v1/origins/') && !t.includes('://');
    if (!p || !base || !tmplOk(m.initialization_template) || !tmplOk(m.segment_template)) return null;
    const fill = (t, ts) => base + t.replace('{{profile_id}}', p.id).replace('{{file_type}}', 'webm').replace('{{segment_timestamp}}', ts);
    const urls = [fill(m.initialization_template)];
    for (let t = (k.start_time_millis || 0) / 1000; t * 1000 < k.end_time_millis && urls.length < 9; t += k.segment_length || 4) urls.push(fill(m.segment_template, t));
    const bufs = await Promise.all(urls.map((u) => fetch(u).then((res) => { if (!res.ok) throw new Error('canvas ' + res.status); return res.arrayBuffer(); })));
    return bufs.reduce((n, b) => n + b.byteLength, 0) <= 8e6 ? bufs : null;
  };
  const attachCanvas = (v, bufs) => {
    const ms = new MediaSource(), url = URL.createObjectURL(ms);
    v.src = url;
    ms.addEventListener('sourceopen', async () => {
      URL.revokeObjectURL(url);
      try {
        const sb = ms.addSourceBuffer(CANVAS_TYPE); sb.mode = 'sequence';
        for (const b of bufs) { sb.appendBuffer(b); await new Promise((ok) => sb.addEventListener('updateend', ok, { once: true })); }
        ms.endOfStream();
      } catch (e) { v.remove(); }
    }, { once: true });
  };
  const lyricCanvas = () => {
    const pane = document.querySelector('.main-view-container');
    const want = localStorage.getItem('office-glass-lyric-canvas') !== '0' && lyricsBox && pane && pane.contains(lyricsBox);
    let v = document.getElementById('og-lyric-canvas');
    if (!want) { if (v) { v.pause(); v.remove(); } return; }
    let uri = null; try { uri = Spicetify.Player.data.item.uri; } catch (e) {}
    if (!uri || !uri.startsWith('spotify:track:') || !Spicetify.GraphQL || !Spicetify.GraphQL.Definitions || !Spicetify.GraphQL.Definitions.canvas) return;
    if (uri !== canvasKey) {
      canvasKey = uri; canvasBufs = null;
      if (v) { v.pause(); v.remove(); v = null; }
      const mine = canvasLoading = loadCanvas(uri).catch(() => null);
      mine.then((bufs) => { if (canvasLoading === mine && canvasKey === uri) { canvasBufs = bufs; lyricCanvas(); } });
      return;
    }
    if (!canvasBufs) return;                                                // none for this song, or still arriving
    if (!v || v.parentElement !== pane) {
      if (v) v.remove();
      v = document.createElement('video'); v.id = 'og-lyric-canvas';
      v.muted = true; v.loop = true; v.playsInline = true; v.setAttribute('aria-hidden', 'true');
      pane.prepend(v);                                                     // above the wallpaper, under the words
      attachCanvas(v, canvasBufs);
    }
    let playing = true; try { playing = Spicetify.Player.isPlaying(); } catch (e) {}
    if (playing && v.paused) v.play().catch(() => {}); else if (!playing && !v.paused) v.pause();
  };
  const tick = () => {
    const root = document.querySelector('[style*="--cinema-mode-bg-color-from"]');
    document.documentElement.classList.toggle('office-glass-fs', !!root);
    labelLyrics();
    pickVoice();
    flatArt();
    artistVisuals();
    lyricCanvas();
    tagAbout();
    let playingNow = true; try { playingNow = Spicetify.Player.isPlaying(); } catch (e) {}
    document.documentElement.classList.toggle('office-glass-paused', !playingNow);
    if (!root) { lastHex = null; colourFromCover(); return; }
    if (!document.getElementById('office-glass-capsules')) {
      const row = document.createElement('div'); row.id = 'office-glass-capsules';
      row.innerHTML = '<i><u></u></i><i><u></u></i><i><u></u></i><i><u></u></i><i><u></u></i><i><u></u></i>';
      const bg = root.firstElementChild;
      if (bg && bg.nextSibling) root.insertBefore(row, bg.nextSibling); else root.appendChild(row);
    }
    startFrames();
    // Spotify moves the artwork when the dock hides (idle layout): follow it instead of assuming a position
    const art = root.querySelector('.cover-art');
    if (art) {
      const a = art.getBoundingClientRect(), r0 = root.getBoundingClientRect();
      // A Canvas video makes Spotify swap the big square for a thumbnail. Measuring that shrinks the whole stage:
      // the capsules blow up, the title falls off the bottom ("full screen broken"). The stage
      // is only ever measured from a real artwork square, and otherwise keeps the geometry it already has.
      if (a.height > Math.min(320, r0.height * 0.30)) {
        root.style.setProperty('--og-mid', Math.round(a.top - r0.top + a.height / 2) + 'px');
        root.style.setProperty('--og-bottom', Math.round(a.bottom - r0.top) + 'px');
        root.style.setProperty('--og-art', Math.round(a.width) + 'px');   // a Canvas video is clamped to this square
      }
    }
    // the artist's photograph, far behind the glass
    if (!document.getElementById('office-glass-scene')) { const sc = document.createElement('div'); sc.id = 'office-glass-scene'; root.insertBefore(sc, root.firstElementChild ? root.firstElementChild.nextSibling : null); }
    // the wallpaper stage behind the artwork
    if (!document.getElementById('office-glass-wall')) { const w = document.createElement('div'); w.id = 'office-glass-wall'; root.insertBefore(w, document.getElementById('office-glass-capsules')); }
    // title block: song and artist in proper type under the artwork
    let tb = document.getElementById('office-glass-title');
    if (!tb) { tb = document.createElement('div'); tb.id = 'office-glass-title'; tb.innerHTML = '<b></b><span></span><div class="beads"><em class="q"><svg viewBox="0 0 16 16"><path d="M2 6.200v3.600M5 3.800v8.400M8 1.800v12.400M11 4.400v7.200M14 6.600v2.800" stroke="currentColor" stroke-width="1.700" stroke-linecap="round" fill="none"/></svg>Lossless</em><em class="l"><svg viewBox="0 0 24 24"><path fill="currentColor" d="M12 21.200l-1.500-1.300C5.200 15.200 2 12.300 2 8.700 2 5.900 4.200 3.800 7 3.800c1.600 0 3.100.700 4 1.900l1 1.200 1-1.200c.900-1.200 2.400-1.900 4-1.900 2.800 0 5 2.100 5 4.900 0 3.600-3.200 6.500-8.500 11.200L12 21.200z"/></svg>Liked</em><em class="p"><svg viewBox="0 0 16 16"><path fill="currentColor" d="M3.500 2.500h3v11h-3zM9.500 2.500h3v11h-3z"/></svg>Paused</em></div><div id="office-glass-progress"><u></u></div>'; root.appendChild(tb); }
    try {
      const it = Spicetify.Player.data && Spicetify.Player.data.item;
      if (it) {
        const name = it.name || '', by = (it.artists || []).map((a) => a.name).join(', ');
        if (tb.children[0].textContent !== name && !window.__ogSwapping) {
          // a song skip is a choreographed exit and entrance, not a text swap: the old title fades and lifts (0.24 s),
          // then the new title, artist and portrait rise together with the artwork ("song skip could be cleaner")
          window.__ogSwapping = true;
          tb.classList.remove('office-glass-in'); tb.classList.add('office-glass-out');
          const since = performance.now() - (window.__ogSongChangedAt || 0);
          setTimeout(() => {
            tb.children[0].textContent = name; tb.children[1].textContent = by; tb.classList.remove('has-artist');
            // the portrait bead comes from artistVisuals(), which may still be in flight on a fast skip
            const face = () => { if (window.__ogArtistFace && tb.children[1].textContent === by) { tb.style.setProperty('--og-artist', 'url("' + window.__ogArtistFace + '")'); tb.classList.add('has-artist'); } };
            face(); setTimeout(face, 700); setTimeout(face, 1800);
            tb.classList.remove('office-glass-out');
            for (const el of [tb, art]) { if (!el) continue; el.classList.remove('office-glass-in'); void el.offsetWidth; el.classList.add('office-glass-in'); }
            window.__ogSwapping = false;
          }, Math.max(0, 240 - since));
        } else if (tb.children[1].textContent !== by && !window.__ogSwapping) tb.children[1].textContent = by;
      }
    } catch (e) {}
    // idle layout = Spotify has hidden the dock and moved the artwork down; show our hairline progress then
    document.documentElement.classList.toggle('office-glass-idle', !document.querySelector('.Root__now-playing-bar aside') || (art && art.getBoundingClientRect().top > 185));
    try {
      const bar = tb.querySelector('#office-glass-progress u'), dur = Spicetify.Player.getDuration();
      if (bar && dur > 0) bar.style.width = Math.min(100, Spicetify.Player.getProgress() / dur * 100).toFixed(2) + '%';
    } catch (e) {}
    // state beads and the paused mood, read from Spotify's own dock so they are always true
    const widget = document.querySelector('aside [data-testid="now-playing-widget"]');
    tb.classList.toggle('lossless', !!widget && /lossless/i.test(widget.textContent || ''));
    tb.classList.toggle('liked', !!widget && !!widget.querySelector('button[aria-checked="true"]'));
    const m = /--cinema-mode-bg-color-from:\s*#([0-9a-f]{6})/i.exec(root.getAttribute('style') || '');
    if (!m || m[1] === lastHex) return;
    lastHex = m[1]; lastCoverUrl = null;
    try { const u = Spicetify.Player.data.item.uri; (window.__ogSeenHex = window.__ogSeenHex || {})[u] = m[1]; } catch (e) {}   // remembered for the app view
    const n = parseInt(m[1], 16);
    applyColour(n >> 16, (n >> 8) & 255, n & 255);
  };
  // the song's typographic voice, like a concert changing its stage type for every act.
  // Chosen from the song's hue, how colourful it is, and its tempo (tempo arrives a moment after the colour).
  let voiceHue = 0, voiceSat = 0;
  const pickVoice = () => {
    if (window.__ogVoiceLock) return;                                      // voices_shot.js holds a voice while it photographs it
    const g = window.__officeBeats; let id = null; try { id = Spicetify.Player.data.item.uri.split(':')[2]; } catch (e) {}
    const tempo = g && g.id === id && g.tempo ? g.tempo : 0, h = voiceHue, fast = tempo >= 124, slow = tempo > 0 && tempo < 96;
    let v;
    if (voiceSat < 0.14) v = 'gallery';                                   // black and white covers: thin, wide, gallery type
    else if (h >= 0.78 || h < 0.03) v = fast ? 'neon' : 'velvet';           // pinks, magentas, deep reds
    else if (h < 0.17) v = fast ? 'poster' : 'classic';                     // reds, oranges, golds
    else if (h < 0.45) v = slow ? 'classic' : 'velvet';                     // greens
    else v = slow || !fast ? 'couture' : 'poster';                          // teals, blues, violets
    if (document.documentElement.dataset.voice !== v) document.documentElement.dataset.voice = v;
  };
  // ---- the wallpaper's own colour, so any picture tints to the song ----
  // The stage tints the wallpaper with hue-rotate, which turns every colour in it by the same angle. To land on the
  // song's colour it has to know where the picture starts. Both shipped pictures are teal, about 186 degrees, and
  // that was a constant; now the picture is measured once, in the page, from the embedded copy (a data: URI, so
  // nothing is fetched and the canvas is readable). The strongest 10-degree band of colour wins, weighted by how
  // vivid each pixel is, then a vector mean within 30 degrees of it refines the angle; greys and blacks carry no
  // hue and are skipped. Checked against renders at 0, 120 and 280 degrees: within 3 degrees each time.
  // A picture with no clear colour keeps 186, where the old constant put it. The settings panel calls it again when
  // someone picks their own picture; only the newest call may write, so a slow first measurement cannot win late.
  let wallBase = 186, lastRgb = null, wallCall = 0;
  const measureWall = (tries, call = ++wallCall) => {
    const m = /url\(["']?(data:image\/[^"')]+)/.exec(getComputedStyle(document.documentElement).getPropertyValue('--og-wall'));
    if (!m) { if (tries > 0) setTimeout(() => measureWall(tries - 1, call), 1000); return; }   // the stylesheet may not be in yet
    const img = new Image();
    img.onload = () => { try {
      if (call !== wallCall) return;
      const W = 64, H = 33, c = document.createElement('canvas'); c.width = W; c.height = H;
      const x = c.getContext('2d', { willReadFrequently: true }); x.drawImage(img, 0, 0, W, H);
      const px = x.getImageData(0, 0, W, H).data, bins = new Array(36).fill(0), pts = [];
      for (let i = 0; i < px.length; i += 4) {
        const [h, sa, v] = hsv(px[i], px[i + 1], px[i + 2]), w = sa * v;
        if (w < 0.08) continue;
        bins[Math.floor(h * 36) % 36] += w; pts.push([h * 360, w]);
      }
      let peak = 0, best = -1;
      for (let i = 0; i < 36; i++) { const sm = bins[(i + 35) % 36] + bins[i] * 2 + bins[(i + 1) % 36]; if (sm > best) { best = sm; peak = i * 10 + 5; } }
      if (best < 3) { wallBase = 186; delete document.documentElement.dataset.ogWallHue; if (lastRgb) applyColour(...lastRgb); return; }   // no clear colour: keep 186
      let cx = 0, cy = 0;
      for (const [h, w] of pts) if (Math.abs(((h - peak + 540) % 360) - 180) <= 30) { cx += w * Math.cos(h * Math.PI / 180); cy += w * Math.sin(h * Math.PI / 180); }
      wallBase = Math.round(((Math.atan2(cy, cx) * 180 / Math.PI) + 360) % 360);
      document.documentElement.dataset.ogWallHue = wallBase;              // visible in the inspector, for anyone checking
      if (lastRgb) applyColour(...lastRgb);
    } catch (e) {} };
    img.src = m[1];
  };
  measureWall(10);
  window.__ogMeasureWall = () => measureWall(3);
  window.__ogReapplyColour = () => { if (lastRgb) applyColour(...lastRgb); };
  const applyColour = (r0, g0, b0) => {
    lastRgb = [r0, g0, b0];
    // "One colour, always" in the settings: like a car's ambient light, the picked colour stands in for the song's
    // everywhere the song's colour goes (the glass, the type, the lights). The song's own is kept for switching back.
    const pick = localStorage.getItem('office-glass-colour-pick') || '';
    if (/^#[0-9a-f]{6}$/i.test(pick)) [r0, g0, b0] = [1, 3, 5].map((i) => parseInt(pick.slice(i, i + 2), 16));
    let [h, sa] = hsv(r0, g0, b0);
    voiceHue = h; voiceSat = sa;
    if (h > 0.14 && h < 0.25) h = h < 0.19 ? 0.125 : 0.29;      // yellow-green reads sickly: commit to gold or green, like the lights
    const de = document.documentElement.style;
    de.setProperty('--og-hue', (Math.round(h * 360) - wallBase) + 'deg');
    de.setProperty('--og-sat', sa < 0.12 ? '0.25' : String(Math.min(1.6, 0.9 + sa * 0.8).toFixed(2)));
    if (sa < 0.12) { de.setProperty('--gs', 'rgb(150 165 175)'); de.setProperty('--gs2', 'rgb(90 110 130)'); return; }   // grey songs: cool silver glass
    de.setProperty('--gs', 'rgb(' + rgb(h, Math.max(0.72, Math.min(0.92, sa + 0.25)), 0.96) + ')');
    de.setProperty('--gs2', 'rgb(' + rgb(h + (h < 0.17 || h > 0.75 ? -0.07 : 0.07), 0.7, 0.7) + ')');
  };
  // ---- beat reverb: the capsules swell softly on the beat, rippling outward from the centre ----
  // govee-dj.js shares each song's beat map on window.__officeBeats ({ id, beats: [{ t, s }] }).
  const ATTACK = 0.14, TAIL = 0.95, RIPPLE = 0.05;           // seconds; softer attack and a longer tail ("pulse is overwhelming")
  const swellDepth = () => { const v = parseFloat(localStorage.getItem('office-glass-swell') || ''); return isNaN(v) ? 0.0045 : v; };   // was 0.012
  // dt is measured from ATTACK seconds BEFORE the beat, so the swell peaks exactly on it instead of just after
  const env = (dt) => { if (dt < 0) return 0; if (dt < ATTACK) { const x = dt / ATTACK; return x * x * (3 - 2 * x); } return Math.exp(-(dt - ATTACK) / TAIL); };
  let idx = 0, lastId = null, likeWaveAt = 0;
  const startFrames = () => {
    if (document.hidden || reducedMotion.matches || window.__officeGlassRaf) return;
    window.__officeGlassRaf = requestAnimationFrame(frame);
  };
  const frame = () => {
    window.__officeGlassRaf = 0;
    const row = document.getElementById('office-glass-capsules');
    if (!row || document.hidden) return;
    const g = window.__officeBeats;
    let playing = false; try { playing = Spicetify.Player.isPlaying(); } catch (e) {}
    const caps = row.children;
    if ((!g || !g.beats || !g.beats.length || !playing) && !likeWaveAt) {
      for (const c of caps) { c.style.transform = ''; c.firstChild.style.opacity = 0; }
      return;
    }
    const gb = g && g.beats && g.beats.length && playing ? g.beats : [];
    if (g && g.id !== lastId) { lastId = g.id; idx = 0; }
    const offset = (parseInt(localStorage.getItem('office-glass-beat-offset-ms') || '0', 10) || 0) / 1000;
    const pos = Spicetify.Player.getProgress() / 1000 - offset + ATTACK;
    if (idx >= gb.length) idx = 0;
    while (idx < gb.length - 1 && gb[idx + 1].t <= pos + 0.001) idx++;
    while (idx > 0 && gb[idx].t > pos) idx--;
    for (let i = 0; i < caps.length; i++) {
      const dist = Math.abs(i - (caps.length - 1) / 2);          // 0.5, 1.5, 2.5 from the centre
      const p = pos - dist * RIPPLE;
      let e = 0;
      for (let k = idx; k >= 0 && k > idx - 3 && k < gb.length; k--) e = Math.max(e, gb[k].s * env(p - gb[k].t));
      if (likeWaveAt) {                                                     // a like: one big wave of light, centre outward
        const w = (performance.now() - likeWaveAt) / 1000 - dist * 0.11;
        if (w > 0 && w < 2.0) e = Math.max(e, 1.5 * (w < 0.22 ? (w / 0.22) * (w / 0.22) * (3 - 2 * w / 0.22) : Math.exp(-(w - 0.22) / 0.55)));
        if (i === caps.length - 1 && w > 2.2) likeWaveAt = 0;
      }
      caps[i].style.transform = 'scale(' + (1 + 0.010 * e).toFixed(4) + ',' + (1 + 0.022 * e).toFixed(4) + ')';
      if (i === 2) document.documentElement.style.setProperty('--og-swell', (1 + swellDepth() * e).toFixed(4));
      caps[i].firstChild.style.opacity = (0.55 * e).toFixed(3);
    }
    startFrames();
  };
  cancelAnimationFrame(window.__officeGlassRaf);
  window.__officeGlassRaf = 0;

  // ---- the moment you like a song ----
  const HEART = '<svg viewBox="0 0 24 24"><path d="M12 21.2l-1.5-1.3C5.2 15.2 2 12.3 2 8.7 2 5.9 4.2 3.8 7 3.8c1.6 0 3.1.7 4 1.9l1 1.2 1-1.2c.9-1.2 2.400-1.9 4-1.9 2.800 0 5 2.100 5 4.900 0 3.600-3.200 6.500-8.500 11.200L12 21.2z"/></svg>';
  const celebrateLike = (x, y) => {
    let fx = document.getElementById('office-glass-fx');
    if (!fx) { fx = document.createElement('div'); fx.id = 'office-glass-fx'; document.body.appendChild(fx); }
    const add = (cls, html) => { const el = document.createElement('div'); el.className = cls; el.style.left = x + 'px'; el.style.top = y + 'px'; if (html) el.innerHTML = html; fx.appendChild(el); return el; };
    const done = (el, anim) => { anim.onfinish = () => el.remove(); };
    const ease = 'cubic-bezier(0.2, 0.7, 0.2, 1)';
    { const ring = add('ring'); done(ring, ring.animate([{ transform: 'scale(0.7)', opacity: 0.55 }, { transform: 'scale(2.6)', opacity: 0 }], { duration: 1100, easing: ease, fill: 'both' })); }
    for (let k = 0; k < 7; k++) {
      const a = -Math.PI / 2 + (Math.random() - 0.5) * 2.4, d = 50 + Math.random() * 90, sc = 0.35 + Math.random() * 0.5;
      const s = add('spark' + (k % 3 === 0 ? ' w' : ''));
      done(s, s.animate([
        { transform: 'translate(0,0) scale(' + sc + ')', opacity: 1 },
        { transform: 'translate(' + (Math.cos(a) * d * 0.7).toFixed(0) + 'px,' + (Math.sin(a) * d).toFixed(0) + 'px) scale(' + (sc * 0.9) + ')', opacity: 0.9, offset: 0.55 },
        { transform: 'translate(' + (Math.cos(a) * d).toFixed(0) + 'px,' + (Math.sin(a) * d - 40).toFixed(0) + 'px) scale(0.1)', opacity: 0 }
      ], { duration: 1000 + Math.random() * 700, delay: Math.random() * 120, easing: ease, fill: 'both' }));
    }
    likeWaveAt = performance.now();
    startFrames();
    const de = document.documentElement; de.classList.remove('office-glass-liked-burst'); void de.offsetWidth; de.classList.add('office-glass-liked-burst');
    clearTimeout(window.__officeGlassBurst); window.__officeGlassBurst = setTimeout(() => de.classList.remove('office-glass-liked-burst'), 1700);
  };
  window.__officeGlassCelebrate = celebrateLike;                           // so the console can fire it for a look
  if (!window.__officeGlassLikeHooked) {
    window.__officeGlassLikeHooked = true;
    document.addEventListener('click', (ev) => {
      const btn = ev.target && ev.target.closest && ev.target.closest('button[aria-checked]');
      if (!btn || !btn.closest('[data-testid="now-playing-widget"], .main-nowPlayingView-panel, .main-nowPlayingWidget-nowPlaying')) return;
      const was = btn.getAttribute('aria-checked') === 'true';
      if (was) return;                                                     // un-liking stays quiet
      if (/hide/i.test(btn.getAttribute('aria-label') || '')) return;      // "Hide in this playlist" sits beside it and is not a like
      const r = btn.getBoundingClientRect();
      setTimeout(() => window.__officeGlassCelebrate(r.left + r.width / 2, r.top + r.height / 2), 60);
    }, true);
  }

  // paused dock: hide after 6 s without a touch or mouse move, show again on any
  if (!window.__officeGlassDockHooked) {
    window.__officeGlassDockHooked = true;
    let last = performance.now();
    const wake = () => { last = performance.now(); document.documentElement.classList.remove('office-glass-hidedock'); };
    for (const ev of ['pointermove', 'pointerdown', 'touchstart', 'keydown', 'wheel']) document.addEventListener(ev, wake, { passive: true, capture: true });
    setInterval(() => {
      let playing = true; try { playing = Spicetify.Player.isPlaying(); } catch (e) {}
      const fs = document.documentElement.classList.contains('office-glass-fs');
      if (fs && !playing && performance.now() - last > 6000) document.documentElement.classList.add('office-glass-hidedock');
      else if (playing) document.documentElement.classList.remove('office-glass-hidedock');
    }, 500);
  }
  // beat map on its own: on a machine without govee-dj.js nobody fills window.__officeBeats, so fetch it here
  let ownBeatFor = null;
  const ownBeatMap = async () => {
    let id = null; try { const u = Spicetify.Player.data.item.uri; id = u.startsWith('spotify:track:') ? u.split(':')[2] : null; } catch (e) {}
    if (!id || ownBeatFor === id || (window.__officeBeats && window.__officeBeats.id === id)) return;
    ownBeatFor = id;
    await new Promise((r) => setTimeout(r, 2500));                          // give a lights extension first claim
    if (window.__officeBeats && window.__officeBeats.id === id) return;
    try {
      const tok = (Spicetify.Platform.Session && Spicetify.Platform.Session.accessToken) || (await Spicetify.Platform.AuthorizationAPI.getState()).token.accessToken;
      const r = await fetch('https://spclient.wg.spotify.com/audio-attributes/v1/audio-analysis/' + id + '?format=json', { headers: { Authorization: 'Bearer ' + tok } });
      if (!r.ok) throw new Error('HTTP ' + r.status);
      const a = await r.json(), bars = new Set((a.bars || []).map((x) => x.start));
      window.__officeBeats = { id, tempo: a.track && a.track.tempo, beats: (a.beats || []).map((b) => ({ t: b.start, s: bars.has(b.start) ? 1 : 0.5 })) };
      startFrames();
    } catch (e) { /* no analysis for this track: the glass simply stays still */ }
  };
  setInterval(ownBeatMap, 3000);

  if (!window.__ogSkipHooked) {
    window.__ogSkipHooked = true;
    Spicetify.Player.addEventListener('songchange', () => {
      window.__ogSongChangedAt = performance.now();
      const tb = document.getElementById('office-glass-title'); if (tb) { tb.classList.remove('office-glass-in'); tb.classList.add('office-glass-out'); }
    });
  }
  // finger or mouse: hover states only make sense for a mouse (see touch.css)
  // touch mode: a USB touchscreen on macOS reports NO touch points and sends mouse events, so it cannot be detected.
  // localStorage['office-glass-touch'] = '1' turns it on for good (a wall-mounted touch screen), '0' off.
  {
    const set = localStorage.getItem('office-glass-touch');
    const on = set === '1' || (set !== '0' && matchMedia('(pointer: coarse)').matches);
    document.documentElement.classList.toggle('office-glass-touch', on);
    // the size of everything the theme draws itself: 1 suits a 16 inch screen, less for a big desk monitor
    const ui = parseFloat(localStorage.getItem('office-glass-ui-scale') || '1');
    document.documentElement.style.setProperty('--og-ui', isNaN(ui) ? 1 : Math.max(0.6, Math.min(1.4, ui)));
  }
  if (!window.__ogTouchHooked) {
    window.__ogTouchHooked = true;
    document.addEventListener('touchstart', () => document.documentElement.classList.add('office-glass-touch'), { passive: true, capture: true });
    document.addEventListener('pointerdown', (e) => { if (e.pointerType === 'mouse' && localStorage.getItem('office-glass-touch') !== '1') document.documentElement.classList.remove('office-glass-touch'); }, { passive: true, capture: true });
  }
  if (!window.__officeGlassVisibilityHooked) {
    window.__officeGlassVisibilityHooked = true;
    document.addEventListener('visibilitychange', () => { if (!document.hidden) { tick(); startFrames(); } });
  }
  clearInterval(window.__officeGlassLyricTimer);
  window.__officeGlassLyricTimer = setInterval(() => { if (lyricsBox && lyricTimes) labelLyrics(); }, 100);
  clearInterval(window.__officeGlassTimer);
  window.__officeGlassTimer = setInterval(tick, 600);
  tick();
})();
